apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: wasm-filter-independent
  namespace: kube-system
spec:
  resources:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: wasm_proxy_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: wasm_proxy
          codec_type: AUTO
          route_config:
            name: wasm_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: test_backend_cluster
                  timeout: 30s
          http_filters:
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                name: oxy_money_auth_filter
                root_id: oxy_auth_root
                vm_config:
                  vm_id: oxy_money_auth_vm
                  runtime: envoy.wasm.runtime.v8
                  code:
                    local:
                      filename: "/var/lib/cilium/wasm/oxy_money_auth.wasm"
                  allow_precompiled: true
                configuration:
                  "@type": type.googleapis.com/google.protobuf.StringValue
                  value: '{"environment": "local"}'
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: test_backend_cluster
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: test_backend_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.96.242.44
                port_value: 8080
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-proxy
  namespace: cilium-test
spec:
  type: ClusterIP
  selector:
    k8s-app: cilium-envoy
  ports:
  - name: wasm-http
    port: 80
    targetPort: 10000
    protocol: TCP
